on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      runner:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-22.04   # inputs.runs-on

    # Prevent two runs for one PR:
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name

    steps:
    - uses: actions/checkout@v3
    - uses: lingy-lang/gha-perl-test-runner@main

