on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      runner:
        required: true
        type: string

jobs:
  test:
    runs-on: inputs.runs_on
    # runs-on: ubuntu-22.04

    # Prevent two runs for one PR:
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name

    steps:
    - uses: actions/checkout@v3
    - uses: lingy-lang/gha-perl-test-runner@main

